In [34]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

In [49]:
train_data_set=pd.read_csv("train.csv")
test_data_set=pd.read_csv("test.csv")
test_data_set.head()

ID     Date       Opponent Is_Home_or_Away Is_Opponent_in_AP25_Preseason  \
0  25   9/2/17         Temple            Home                           Out   
1  26   9/9/17        Georgia            Home                            In   
2  27  9/16/17  BostonCollege            Away                           Out   
3  28  9/23/17  MichiganState            Away                           Out   
4  29  9/30/17      MiamiOhio            Home                           Out   

    Media Label  
0   1-NBC   Win  
1   1-NBC  Lose  
2  2-ESPN   Win  
3   3-FOX   Win  
4   1-NBC   Win

In [50]:
train_data_set=train_data_set.drop(["Date","ID","Opponent"], axis=1)
test_data_set=test_data_set.drop(["Date","ID","Opponent"], axis=1)
train_data_set.head()

Is_Home_or_Away Is_Opponent_in_AP25_Preseason  Media Label
0            Home                           Out  1-NBC   Win
1            Away                           Out  4-ABC   Win
2            Home                            In  1-NBC   Win
3            Home                           Out  1-NBC   Win
4            Away                            In  4-ABC  Lose

In [37]:
#changing categorical data to numerical

for col in train_data_set.columns:
    train_data_set[col]=pd.Categorical(train_data_set[col])
    train_data_set[col]=train_data_set[col].cat.codes
    
train_data_set.head()

Is_Home_or_Away  Is_Opponent_in_AP25_Preseason  Media  Label
0                1                              1      0      1
1                0                              1      3      1
2                1                              0      0      1
3                1                              1      0      1
4                0                              0      3      0

In [38]:

for col in test_data_set.columns:
    test_data_set[col]=pd.Categorical(test_data_set[col])
    test_data_set[col]=test_data_set[col].cat.codes
    
test_data_set=test_data_set

In [39]:
## ceating the training and testing data and labels

train_x= train_data_set[train_data_set.columns[:-1]].values
train_y=train_data_set['Label'].values
train_x


array([[1, 1, 0],
       [0, 1, 3],
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 3],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 3],
       [0, 1, 3],
       [1, 1, 0],
       [0, 1, 0],
       [0, 0, 2],
       [0, 1, 3],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       [0, 1, 3],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 4],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 3]], dtype=int8)

In [40]:
test_x=test_data_set[test_data_set.columns[:-1]].values
test_true_label=test_data_set["Label"].values
test_x


array([[1, 1, 0],
       [1, 0, 0],
       [0, 1, 1],
       [0, 1, 2],
       [1, 1, 0],
       [0, 1, 3],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 0, 3],
       [1, 1, 0],
       [0, 0, 3]], dtype=int8)

In [41]:
test_true_label

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int8)

In [42]:
#Naive baiyes prediction

model=GaussianNB()
model.fit(np.array(train_x),train_y)
predicted_labels=model.predict(test_x)

## Question 1

In [43]:
predicted_labels

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0], dtype=int8)

In [44]:
# Calculation of accuracy and fscore

def creatsum(name, y, y_pred):
    headers = {
        'Accuracy': accuracy_score, 
        'F1_Score': f1_score, 
        'Precision': precision_score, 
        'Recall': recall_score
    }
    
    with open('{}.csv'.format(name), 'w') as summary:
        print(','.join(headers.keys()), file=summary)
        summary.write(','.join(['{:3.3f}'.format(metric(y, y_pred)) for metric in headers.values()]))

#print("Accuracy",metrics.accuracy_score(test_true_label,predicted_labels))
creatsum("Nb",test_true_label,predicted_labels)

## Question 2

In [45]:
### the result obtain by using Naive Bayes Classificaiton

Nb_summary=pd.read_csv("Nb.csv")
Nb_summary

Accuracy  F1_Score  Precision  Recall
0     0.917     0.941        1.0   0.889

In [46]:
### the result obtain by previous assigment---- Decision tree by using ID3-----

id_summary=pd.read_csv("id3.csv")
id_summary

Accuracy  F1 Score  Precision  Recall
0     0.833     0.889      0.889   0.889

In [47]:
### the result obtain by previous assigment---- Decision tree by using c4.5-----

c45_summary=pd.read_csv("c45.csv")
c45_summary

Accuracy  F1 Score  Precision  Recall
0     0.917     0.947        0.9     1.0

## Question 3

As we have calculated the f score accuracy etc in previous assigment on the same dataset with algorith like C4.5 and ID3

from the above score we can observe that accuracy in case of Navie Bayes and C4.5 algorithm is same while the accuracy does go down in ID3


from the above score we can come to a conclusion that Navie Bayes performs very well compared to Decision Tree and it's the best(when we consider precision and recall) while, ID3 alogrithm performs worst in all three.

These could be due to following reasons.

NB: work well with small dataset and has less overfitting while on the other hand decision tree need more dataset to perform well and algorithm like ID3 does not work well continuous and discrete features.



------------Link for code-------------
https://github.com/rpm360/MLassignment/blob/master/HW4/MLHW4.ipynb